sudo: false
language: node_js

cache:
  directories:
  - "node_modules" # NPM packages

matrix:
  include:
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1
    - os: osx
      node_js: "8"
      env: NO_WATCH_TESTS=1
  allow_failures:
    - os: osx
  fast_finish: true
